// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: finances.sql

package database

import (
	"context"
	"database/sql"
)

const addTransaction = `-- name: AddTransaction :one
INSERT INTO finances (id, timestamp,date_transaction, ammount_cent, type, description, catagory)
VALUES(
    gen_random_UUID(),
    NOW,
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, timestamp, date_transaction, ammount_cent, type, description, catagory
`

type AddTransactionParams struct {
	DateTransaction string
	AmmountCent     int32
	Type            sql.NullString
	Description     string
	Catagory        string
}

func (q *Queries) AddTransaction(ctx context.Context, arg AddTransactionParams) (Finance, error) {
	row := q.db.QueryRowContext(ctx, addTransaction,
		arg.DateTransaction,
		arg.AmmountCent,
		arg.Type,
		arg.Description,
		arg.Catagory,
	)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.DateTransaction,
		&i.AmmountCent,
		&i.Type,
		&i.Description,
		&i.Catagory,
	)
	return i, err
}
