// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Finance struct {
	ID              uuid.UUID
	Timestamp       time.Time
	DateTransaction time.Time
	AmmountCent     int32
	Type            string
	Description     string
	Catagory        string
}

type Timeregistration struct {
	ID            uuid.UUID
	Timestamp     time.Time
	DateActivity  time.Time
	LengthMinutes int32
	Description   string
	Catagory      string
}

type User struct {
	ID                     uuid.UUID
	Name                   string
	HashedPassword         string
	AccessFinance          bool
	AccessTimeregistration bool
	Administrator          bool
}
