// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Finance struct {
	ID              uuid.UUID
	Timestamp       time.Time
	DateTransaction string
	AmmountCent     int32
	Type            sql.NullString
	Description     string
	Catagory        string
}

type Timeregistration struct {
	ID            uuid.UUID
	Timestamp     time.Time
	DateActivity  string
	LengthMinutes int32
	Description   string
	Catagory      string
}
