// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tijdregistratie.sql

package database

import (
	"context"
)

const addTimeRegistration = `-- name: AddTimeRegistration :one
INSERT INTO timeregistration (id, timestamp, date_activity, length_minutes, description, catagory)
VALUES(
    gen_random_UUID(),
    NOW,
    $1,
    $2,
    $3,
    $4
)
RETURNING id, timestamp, date_activity, length_minutes, description, catagory
`

type AddTimeRegistrationParams struct {
	DateActivity  string
	LengthMinutes int32
	Description   string
	Catagory      string
}

func (q *Queries) AddTimeRegistration(ctx context.Context, arg AddTimeRegistrationParams) (Timeregistration, error) {
	row := q.db.QueryRowContext(ctx, addTimeRegistration,
		arg.DateActivity,
		arg.LengthMinutes,
		arg.Description,
		arg.Catagory,
	)
	var i Timeregistration
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.DateActivity,
		&i.LengthMinutes,
		&i.Description,
		&i.Catagory,
	)
	return i, err
}
