// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const addAdmin = `-- name: AddAdmin :one
INSERT INTO users(id,name,hashed_password,access_finance,access_timeregistration,administrator)
VALUES(
    gen_random_UUID(),
    $1,
    $2,
    1,
    1,
    1
) 
RETURNING id, name, hashed_password, access_finance, access_timeregistration, administrator
`

type AddAdminParams struct {
	Name           string
	HashedPassword string
}

func (q *Queries) AddAdmin(ctx context.Context, arg AddAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addAdmin, arg.Name, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.AccessFinance,
		&i.AccessTimeregistration,
		&i.Administrator,
	)
	return i, err
}

const addUser = `-- name: AddUser :one
INSERT INTO users(id,name,hashed_password,access_finance,access_timeregistration,administrator)
VALUES(
    gen_random_UUID(),
    $1,
    $2,
    $3,
    $4,
    0
) 
RETURNING id, name, hashed_password, access_finance, access_timeregistration, administrator
`

type AddUserParams struct {
	Name                   string
	HashedPassword         string
	AccessFinance          bool
	AccessTimeregistration bool
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Name,
		arg.HashedPassword,
		arg.AccessFinance,
		arg.AccessTimeregistration,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.AccessFinance,
		&i.AccessTimeregistration,
		&i.Administrator,
	)
	return i, err
}

const login = `-- name: Login :one
SELECT id, name, hashed_password, access_finance, access_timeregistration, administrator FROM users
WHERE name = $1
`

func (q *Queries) Login(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, login, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.AccessFinance,
		&i.AccessTimeregistration,
		&i.Administrator,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
INSERT INTO users(id,name,hashed_password,access_finance,access_timeregistration,administrator)
VALUES(
    gen_random_UUID(),
    $1,
    $2,
    $3,
    $4,
    $5
) 
RETURNING id, name, hashed_password, access_finance, access_timeregistration, administrator
`

type UpdateUserParams struct {
	Name                   string
	HashedPassword         string
	AccessFinance          bool
	AccessTimeregistration bool
	Administrator          bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.HashedPassword,
		arg.AccessFinance,
		arg.AccessTimeregistration,
		arg.Administrator,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.AccessFinance,
		&i.AccessTimeregistration,
		&i.Administrator,
	)
	return i, err
}
