name: Go CI

on: 
  pull_request:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Build CLI
        run: go build -o timetally .

      - name: Make CLI executable
        run: chmod +x ./timetally

      - name: Copy .env.citest to .env
        run: cp .env.citest .env

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U testuser -d testdb; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run DB migrations
        run: ./timetally migrate

      - name: Run tests
        run: go test ./...

      - name: Clean up .env
        run: rm -f .env
